list = ["Apple", "Banana", "Guvava", "Mango", "Kiwi"]
print("Length of list:", len(list))
print("First element:", list[0])
print("Last element:", list[-1])
list.append("Pupaya")
print("Updated list:", list)
list.remove("Guvava")
print("Updated List':", list)
list.sort()
print("Sorted list:", list)
list.pop(1)
print("Updated list:", list)  
list.reverse()
print("Reversed list:", list)
print("Multiplication of list:", list * 2)
list  = list [:4]
print("Sliced list:", list) 
list.clear()
print("Updated List:", list)