file = open("bucket_list.txt !", "w")
file.write("1. Visit The Eiffel Tower\n")
file.write("2. Learn To play The Guitar\n")
file.write("3. Code My Own Game\n")
file.close()
print("Bucket list saved to bucket_list.txt !")
file = open("bucket_list.txt !", "r")
content = file.read()
print("\n===My Bucket List===")
print(content)
file.close()
file = open("bucket_list.txt !", "r")
lines = file.readlines()
print(f"You have {len(lines)} items in your bucket list.")
file.close()
file = open("bucket_list.txt !", "a")
file.write("4. Travel To Japan\n")
file.write("5. Run a 5k Marathon\n")
file.close()
print("\n2 More Items Added!")
file = open("bucket_list.txt !", "r")
print("\n===Updated Bucket List===")
print(file.read())
file.close()
