pasta = ("Pasta Arrabiata", "Italian", 20, "Medium")
biriyani = ("Chicken Biryani", "Indian", 45, "Hard")
print("Recipe 1: ", pasta)
print("Name: ", pasta[0])
print("Cuisine: ", pasta[1])
print("Difficulty: ", pasta[-1])
all_recipies = [pasta, biriyani]
print('\nFirst recipe name: ', all_recipies[0][0])
print('Second recipe time: ', all_recipies[1][2], "mins")
print ("\nPasta Recipe Details:")
for detail in pasta:
    print(" - ", detail)
pasta_ingredients = {"Pasta", "Tomato", "Garlic", "Chili", "Olive Oil", "Garlic"}
biryani_ingredients = {"Rice", "Chicken", "Tomato", "Spices", "Onion", "Garlic"}
print("\nPasta Ingredients:")
print(" - ", pasta_ingredients)
print("\nBiryani Ingredients:")
print(" - ", biryani_ingredients)
print("Total Pasta Ingredients: ", len(pasta_ingredients))
pasta_ingredients.add("Parmesan")
pasta_ingredients.discard("Chili")
print("\nUpdated Pasta Ingredients:")
all_ingredients= pasta_ingredients.union(biryani_ingredients)
common= pasta_ingredients.intersection(biryani_ingredients)
only_pasta= pasta_ingredients.difference(biryani_ingredients)
unique_to_each= pasta_ingredients.symmetric_difference(biryani_ingredients)
print("\nAll Ingredients (union): ", all_ingredients)
print("Common Ingredients(intersection): ", common)
print("Only in Pasta(difference): ", only_pasta)
print("Unique to Each(sym. difference): ", unique_to_each)
